apiVersion: v1
kind: Pod
metadata:
  name: http
  labels:
    app: http-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http-port
          containerPort: 80
      volumeMounts:
        - name: docroot
          mountPath: /usr/share/nginx/html
  volumes:
    - name: docroot
      hostPath:
        path: /opt/simple-k8s-example/src
